package com.github.butterbrother.ews.redirector.oldtestclasses;

import javax.swing.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Отработка механизмов работы с таблицей
 */
public class TablePlay {
    private JPanel UnderTable;
    private JScrollPane TalbeScroll;
    private JTable CustomTable;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Table Play");
        frame.setContentPane(new TablePlay().UnderTable);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        String[] columnNames = {"First Name",
                "Last Name",
                "Sport",
                "# of Years",
                "Vegetarian",
                "Test"};
        String[] combodata = new String[]{"One", "Two", "Three"};
        Object[][] data = {
                {"Kathy", "Smith",
                        "Snowboarding", new Integer(5), new Boolean(false), ""},
                {"John", "Doe",
                        "Rowing", new Integer(3), new Boolean(true), ""},
                {"Sue", "Black",
                        "Knitting", new Integer(2), new Boolean(false), ""},
                {"Jane", "White",
                        "Speed reading", new Integer(20), new Boolean(true), ""},
                {"Joe", "Brown",
                        "Pool", new Integer(10), new Boolean(false), ""}
        };

        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames) {
            @Override
            public Class<?> getColumnClass(int index) {
                if (getColumnName(index).equals("Vegetarian"))
                    return Boolean.class;
                if (getColumnName(index).equals("Test"))
                    return JComboBox.class;
                return super.getColumnClass(index);
            }
        };
        CustomTable = new JTable(tableModel);
        TableColumn column = CustomTable.getColumnModel().getColumn(5);
        column.setCellEditor(new DefaultCellEditor(new JComboBox(combodata)));
    }

    public TablePlay() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        CustomTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        UnderTable = new JPanel();
        UnderTable.setLayout(new BorderLayout(0, 0));
        TalbeScroll = new JScrollPane();
        UnderTable.add(TalbeScroll, BorderLayout.CENTER);
        TalbeScroll.setViewportView(CustomTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return UnderTable;
    }
}
